# Generated by Django 3.2.15 on 2025-03-16 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_auto_20250310_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremetadata',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='scoremetadata',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='scoremetadata',
            name='title',
        ),
        migrations.AlterField(
            model_name='score',
            name='downloaded_video_path',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_coordinate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='generated_score_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_coordinate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='score',
            name='version_information',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='score',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_api.score'),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='scoremetadata',
            name='upload_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
