# Generated by Django 3.2.15 on 2025-03-16 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_auto_20250316_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoremetadata',
            name='score',
        ),
        migrations.AddField(
            model_name='score',
            name='metadata',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='backend_api.scoremetadata'),
        ),
    ]
