# Generated by Django 3.2.15 on 2025-03-16 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_auto_20250316_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scoremetadata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='end_coordinate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='start_coordinate',
            field=models.FloatField(blank=True),
        ),
    ]
