# Generated by Django 3.2.15 on 2025-03-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('generated_score_url', models.URLField()),
                ('version_information', models.TextField()),
                ('video_url', models.URLField()),
                ('downloaded_video_path', models.CharField(max_length=255)),
                ('start_coordinate', models.CharField(max_length=100)),
                ('end_coordinate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoreMetadata',
            fields=[
                ('metadata_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('composer', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('upload_date', models.DateField()),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=255)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.score')),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user'),
        ),
        migrations.CreateModel(
            name='GoogleAuth',
            fields=[
                ('auth_id', models.AutoField(primary_key=True, serialize=False)),
                ('google_id_token', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('token_expiry', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.user')),
            ],
        ),
    ]
